### ISSUE TITLE
v3-beta2 timing issue with node/master

### ISSUE THREAD

**Issue by thoraxe** [detiber/openshift-ansible#10]
- Timing issue during setup of ose3-master.
  The Service openshift-node starts before the openshift-master. This
  means the port 10250 gets occupied by the openshift-node, which lets the
  startup of the master failling. "address already in use"
  Solution: get rid of the timeout and start the node service after the
  master is startet.

As reported by a tester.

Is it possible to make ansible check for service status before continuing with stuff?

**Comment by detiber** [comment]
@thoraxe I'm a bit confused on this, is the user reporting that when restarting the host the services are starting up incorrectly and leading to the error? The installer runs the master config (including starting up services) before it runs the node configuration and startup.

If it is startup ordering related, then we should probably patch up the systemd unit files as follows:
openshift-master
add openshift-node, openshift-sdn-node to Before= 

openshift-node
add openshift-master, openshift-sdn-master to After=

openshift-sdn-node
add openshift-master, openshift-sdn-master to After=

@sdodson thoughts?

**Comment by thoraxe** [comment]
I just pasted what the user reported. I have no other info.

I think the user is claiming that the installer started the node services before the master services and that it resulted in an "address in use" error. However I was under the impression that **only** node consumed 10250 and master didn't use it at all. So I'm very confused how one could get an "address in use" error on that port.

I think the error report is bogus but we can go back to the user with questions if need be.

**Comment by sdodson** [comment]
@detiber That sounds good, I haven't added sdNotify to openshift-sdn but I can submit that too. I think given they don't take a significant amount of time to startup it's not a huge risk without them in place. I was also going to add RequiredBy in the [Install] section, I'm having a debate with myself if we want to enforce requirements or just enforce ordering. I'm going to build a test set of packages and verify if package install order affects this or not.

Take a look at these two commits.
https://github.com/sdodson/origin/commit/683263e15d53dd205de40bff431c4b61bb06e177
https://github.com/sdodson/openshift-sdn/commit/b633626b336712822b862549a6e35743e5a57a87

**Comment by sdodson** [comment]
Discussed this with some of the folks in #systemd and they suggest that the [Install] section is really meant for runlevel like targets. I've changed things around since those commits, I'll do some quick testing and then submit PRs.

**Comment by sdodson** [comment]
https://github.com/openshift/openshift-sdn/pull/44 and https://github.com/openshift/origin/pull/1417

**Comment by detiber** [comment]
@sdodson looks good, thanks. I definitely like the idea of enforcing ordering rather than enforcing requirements

**Comment by detiber** [comment]
Closing, since the latest builds have the ordering updates.
