### ISSUE TITLE
node config needs dns setting for skydns

### ISSUE THREAD

**Issue by thoraxe** [detiber/openshift-ansible#11]
So skydns is now running on the master and doing stuff for the .local domain (services, etc).

We are going to move dnsmasq to node2 in the training, and we should probably update the installer to make sure that it tells the nodes to use the master for DNS for containers.

**Comment by thoraxe** [comment]
Has this been implemented?

**Comment by detiber** [comment]
@thoraxe according to https://github.com/openshift/origin/blob/master/pkg/cmd/server/kubernetes/node.go#L235-L237 This should not be needed.

**Comment by detiber** [comment]
Top be more specific, the above code, in conjunction with the following params when creating the node configs: https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_register_nodes/tasks/main.yml#L25-L26

**Comment by detiber** [comment]
And looking at when that change was made, it was after this issue was filed (April 1). So please ignore my previous comments, the issue has been addressed. Closing.
