### ISSUE TITLE
default auth time should be longer

### ISSUE THREAD

**Issue by thoraxe** [detiber/openshift-ansible#18]
The current default auth expiration is 1 hour.

I propose that we raise this to four (4) hours.

We may also want to ask how long once we get to an interactive installer.

**Comment by thoraxe** [comment]
Is this fixed yet?

**Comment by detiber** [comment]
The default is still 1 hour, but it can be set using openshift_master_session_max_seconds, doesn't look like it'll make the cut for the initial installer
