### ISSUE TITLE
accept labels in the configuration somehow

### ISSUE THREAD

**Issue by thoraxe** [detiber/openshift-ansible#24]
It would be nice if the installer would accept labels via configuration somehow. For example, so that "regions" and "zones" could be defined on nodes as they are installed.

**Comment by detiber** [comment]
@thoraxe this _should_ already be available, working on verifying and documenting how to do it now.

**Comment by thoraxe** [comment]
I love me some documentation.

**Comment by detiber** [comment]
heh, well, I found a bug in the implementation, working on getting that fixed (along with getting a fix in for certain AWS vpc configurations that cause issues)

**Comment by detiber** [comment]
Updates for the training docs are here: https://github.com/openshift/training/pull/171 and ansible bugfix is here: https://github.com/openshift/openshift-ansible/pull/199 (it has already been merged to the v3-beta4 branch)
