### ISSUE TITLE
cannot just install master

### ISSUE THREAD

**Issue by thoraxe** [detiber/openshift-ansible#27]
I'm not sure we should do any node registration if we're only installing a master...

**Comment by thoraxe** [comment]
So I changed the title because I realized this is a bug.

If you _just_ try to install a single master, you get a failure on node registration because the list of nodes is empty.

**Comment by detiber** [comment]
@thoraxe I'm sort of hesitant to call this a bug, the playbooks/byo/config.yml playbook is really just a convenience to prevent telling users to run playbooks/byo/openshft-master/config.yml followed by playbooks/byo/openshift-node/config.yml.

If provisioning just a master instance, we should be pointing users to directly run playbooks/byo/openshift-master/config.yml and then having them run playbooks/byo/openshift-node/config.yml when they are ready to provision their node(s).

Once the wrapper is in place, we will probably not even all directly out to byo playbooks and instead just construct the variables needed to call out to the more generic common playbooks.

**Comment by thoraxe** [comment]
Ok, so if you just want a master then run a different playbook. 

I guess we just need to document that in the beta.
