### ISSUE TITLE
installation fails on present node if missing nodes

### ISSUE THREAD

**Issue by thoraxe** [detiber/openshift-ansible#30]
"I’m trying to include node1 into my cluster.   The ansible file for hosts has node[1:2].example.com  

I don’t have a node2 (yet) and because of the missing VM, node1 is not being processed and the whole process stops."

**Comment by detiber** [comment]
I do believe that the ansible host pattern matching expects all hosts to exist when defined in the way we are doing it.

There is no reason we couldn't list both hosts individually, it was just a matter of convenience, not repeating the same information multiple times for both node hosts, and showing the user how to define multiple hosts at once.

**Comment by thoraxe** [comment]
OK, so if the hosts are listed via pattern then this is expected, but if they are listed individually and one does not "work" the other still should?

**Comment by detiber** [comment]
Yes, you should see a failure for the non-present node(s), but the other node(s) should continue just fine.
