### ISSUE TITLE
installer is blowing away existing iptables rules

### ISSUE THREAD

**Issue by thoraxe** [detiber/openshift-ansible#32]
I set up port 53 to be open for dnsmasq on my node2, and, after installation, that rule is gone.

**Comment by thoraxe** [comment]
it does this if the rule isn't in /etc/sysconfig/iptables -- if the rule is already in the iptables file it seems to work.

**Comment by detiber** [comment]
@thoraxe that is correct, the assumption is that the running rules are persisted somewhere (or automatically recreated)
