### ISSUE TITLE
Remove openshift-deployer/deployerKubeConfig

### ISSUE THREAD

**Issue by liggitt** [detiber/openshift-ansible#37]
https://github.com/openshift/origin/pull/2530 switches to using per-namespace service accounts to run deployment pods.

The openshift-deployer.{crt,key,kubeconfig} files are no longer generated and the master config no longer includes the `deployerKubeConfig` field. That should be removed from the template at your convenience once the referenced PR merges.

**Comment by detiber** [comment]
Addressed in upstream repo
