### ISSUE TITLE
Ansible playbook failure -- TASK: [openshift_master | Create master config])

### ISSUE THREAD

**Issue by FlorianOtel** [detiber/openshift-ansible#39]
when running the Ansible playbook I get an error during the "Create master config" task, complaining about the "openshift --write-config" command. 

...
failed: [master1.nuage-vpc253.internal] => {"changed": true, "cmd": ["/usr/bin/openshift", "start", "master", "--write-config", "--config=/etc/openshift/master.yaml", "--portal-net=172.30.17.0/24", "--master=https://ip-172-16-253-120.nuage-vpc253.internal:8443", "--public-master=https://52.24.60.138:8443", "--listen=https://0.0.0.0:8443", "--images=openshift3_beta/ose-${component}:${version}"], "delta": "0:00:00.050166", "end": "2015-06-09 05:17:03.645616", "rc": 1, "start": "2015-06-09 05:17:03.595450", "warnings": []}
stderr: Error: flag needs an argument: --write-config
...

This is a 3-node setup (one master + two minions) on AWS. All nodes have fully working FQDN (via local authoritative DNS sever + forwarder)

The Ansible playbook run log + Ansible hosts file available at:  

https://gist.github.com/FlorianOtel/f2a383e8f9fb18a427a2

**Comment by liggitt** [comment]
--write-config takes the dir to write configuration to

**Comment by rjleaf** [comment]
@FlorianOtel: see this issue: https://github.com/openshift/openshift-ansible/issues/273

Using the proper branch (per the Beta 4 docs) for the ansible repo solves the issue.

**Comment by sosiouxme** [comment]
Beta 4 content has shipped and you won't be able to run the beta3 installer branch anymore (beta4 content eclipses beta3 content).

For enterprise beta installations please follow https://github.com/openshift/training/blob/master/beta-4-setup.md
