### ISSUE TITLE
accept cloud domain flag in installer

### ISSUE THREAD

**Issue by thoraxe** [detiber/openshift-ansible#47]
Apparently you can set things like `OPENSHIFT_ROUTE_SUBDOMAIN=app-v3b4.stg.online.openshift.com` in `/etc/sysconfig/openshift-master`.

We might want the installer to accept that.

**Comment by sdodson** [comment]
We'd do it in the node config file instead.

**Comment by sdodson** [comment]
Reference : https://github.com/openshift/origin/pull/3173

**Comment by thoraxe** [comment]
OK I will try to remember to move this into the config file when I update the materials for RC.

**Comment by detiber** [comment]
closing, since we are tracking this here: https://github.com/openshift/openshift-ansible/issues/282
